MarchandBundle\Entity\Achat:
    type: entity
    table: null
    repositoryClass: MarchandBundle\Repository\AchatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }


    manyToOne:
        user:
            targetEntity: MarchandBundle\Entity\User
            inversedBy: achats
        fruit:
            targetEntity: MarchandBundle\Entity\User
            inversedBy: id



